### ISSUE TITLE
Should create sample for running on Flutter

### ISSUE THREAD

**Issue by anlam87** [synw/iso#1]
This is cool library. i've checked source code in the lib. It's easy to understand. However, it will be perfect if you create sample for running on Flutter. Because as i thought, most of developers use dart to code in Flutter. They want to see visual application sample can run code in background. From my source (isolate_worker), i change to use your library for demo. Please check with the link: https://github.com/fluttervn/isolate_woker/tree/iso

**Comment by synw** [comment]
Hi. The lib works exactly the same in Flutter. Yes including some Flutter examples would be good but I would prefer to link to external examples rather than including it here: I would like to keep the lib lightweight. Your example of downloading is great. I should open a section in the readme to link to external examples.

One example I have is to parse some json in an isolate. I am making a heavy use of this lib in my geojson package: check the [code](https://github.com/synw/geojson/blob/master/lib/src/geojson.dart): in this lib I have several [Flutter examples](https://github.com/synw/geojson/tree/master/example) for parsing heavy geojson (24Mo) and to run geofencing in isolates. Another example is the [Isohttpd](https://github.com/synw/isohttpd) that runs a http server in an isolate.

Tell me when your example is ready and I will create a section in the readme with several examples for Flutter.

**Comment by anlam87** [comment]
I've already completed the example. You can just download and run. However, i've not tested on Android yet. Just for iOS. When testing, if there is any with the example, you can ask me for fixing. Thank you!

**Comment by synw** [comment]
I added a readme to examples and linked from the main readme. I added your example and two others. 

I tested your example:on Android: it's fine and the progress indicator looks good. There is just a minor problem: the downloaded image overflows: maybe your should wrap it in a SingleChildScrollView or something

**Comment by anlam87** [comment]
Image displaying is not a point for this background task subject, so i fix by using fix width/height. By the way, I've updated readme for making example using your library.
